name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  deploy_infra:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          sparse-checkout: azure # Checkout only the azure directory

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Initialize Terraform
        run: terraform init
        working-directory: azure

      - name: Apply Terraform
        run: terraform apply -auto-approve
        working-directory: azure

      - name: Commit state # Save the Terraform state to prevent errors and wrong changes in the future runnings. There are better ways to do this, but this is a simple way to do it.
        run: |
          git config --global user.name 'Eduardo Carisio'
          git config --global user.email 'eduardo_carisio@hotmail.com'
          git add azure/.terraform.lock.hcl
          git add azure/terraform.tfstate
          git commit -m "ðŸ—ï¸ Automatically Updated Terraform State. [skip ci]"
          git push

      - name: Get Publish Profile # Get the publish profile to deploy the app
        run: |
          echo "PUBLISH_PROFILE=$(az webapp deployment list-publishing-profiles -g 'dotnet-hotchocolate-rg' -n 'dotnet-hotchocolate-app' --xml)" >> $GITHUB_OUTPUT
        id: getPublishProfile

  deploy:
    runs-on: ubuntu-latest
    needs: deploy_infra
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'

    - name: Publish
      run: dotnet publish --configuration Release --property:PublishDir=./output

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v3
      with:
        app-name: "dotnet-hotchocolate-app"
        package: ./output
        publish-profile: ${{ steps.getPublishProfile.outputs.PUBLISH_PROFILE }}
    